/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bidmore.view;

import com.bidmore.controller.algorithms.SelectionSort;
import com.bidmore.controller.algorithms.InsertionSort;
import com.bidmore.controller.algorithms.MergeSort;
import com.bidmore.controller.algorithms.BinarySearch;
import java.util.LinkedList;
import java.util.List;
import com.bidmore.model.ProductModel;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nirdeshsubedi
 */
public class bidmoreapp extends javax.swing.JFrame {
    
    private List<ProductModel> productList;
    private java.awt.CardLayout cardLayout;
    

    /**
     * Creates new form mainFrame
     */
    public bidmoreapp() {
        initComponents();
        initializeLayout(); 
        initializeData(); 
    }
    
    
    
    
    /**
     * Initializes the layout of the application by setting up the CardLayout
     * and adding panels for different screens. Each panel is uniquely
     * identified for easy navigation between screens.
     */
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        
        getContentPane().add(pnlLoginScreen, "LoginScreen");
        getContentPane().add(pnlMainScreen, "MainScreen");

        // Start with the loading screen
        loadScreen("LoginScreen");
    }
    
    
    /**
     * Initializes the application's data, including the student list and table.
     * Populates the student list with sample data for demonstration purposes.
     */
    private void initializeData() {
        productList = new LinkedList<>();

        // Registering sample students
        registerProduct(new ProductModel(103,"Old Dollar Coin","Coins",400," Iconic Dollar Bill ","Sam Smith","UPCOMING"));
        registerProduct(new ProductModel(102,"Rolex Watch","Watch",500," Divers Watch ","Sam Smith","UPCOMING"));
        registerProduct(new ProductModel(101,"Pokemon NFT","NFT",100,"  NFT for pokemon lovers","Sam Smith","UPCOMING"));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainScreen = new javax.swing.JPanel();
        tabpaneMain = new javax.swing.JTabbedPane();
        pnlHomeScreen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtpane3 = new javax.swing.JTextPane();
        lblWelcomeMessage = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblWhyChooseUS = new javax.swing.JLabel();
        pnlProductView = new javax.swing.JPanel();
        spTblProduct = new javax.swing.JScrollPane();
        tblProductList = new javax.swing.JTable();
        lblTableHeader = new javax.swing.JLabel();
        btnSortByProductId = new javax.swing.JButton();
        txtFldSearchBar = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        btnSortByName = new javax.swing.JButton();
        btnSortByBasePrice = new javax.swing.JButton();
        pnlAdmin = new javax.swing.JPanel();
        pnlAddProduct = new javax.swing.JPanel();
        txtFldProductID = new javax.swing.JTextField();
        txtFldProductName = new javax.swing.JTextField();
        txtFldBasePrice = new javax.swing.JTextField();
        txtFldAuctioneer = new javax.swing.JTextField();
        txtFldProductType = new javax.swing.JTextField();
        btnUpdate3 = new javax.swing.JButton();
        btnAdd3 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtFldDescription = new javax.swing.JTextField();
        comboBoxStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnDelete4 = new javax.swing.JButton();
        lblAdminHeader = new javax.swing.JLabel();
        pnlAboutUs = new javax.swing.JPanel();
        lblLogoIcon = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPaneCommitment = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPaneCommitment2 = new javax.swing.JTextPane();
        pnlSideBar = new javax.swing.JPanel();
        lblSideBarIcon = new javax.swing.JLabel();
        pnlLoginScreen = new javax.swing.JPanel();
        txtFldLoginUserName = new javax.swing.JTextField();
        pswrdFldLoginPassword = new javax.swing.JPasswordField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblUserIcon = new javax.swing.JLabel();
        lblPasswordIcon = new javax.swing.JLabel();
        lblBidmoreLogo = new javax.swing.JLabel();
        lblloginerror = new javax.swing.JLabel();
        pnlButton = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        lblLoginHeader = new javax.swing.JLabel();

        pnlMainScreen.setPreferredSize(new java.awt.Dimension(1203, 701));

        tabpaneMain.setBackground(new java.awt.Color(51, 102, 255));
        tabpaneMain.setForeground(new java.awt.Color(255, 255, 255));
        tabpaneMain.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabpaneMain.setToolTipText("");
        tabpaneMain.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 24)); // NOI18N
        tabpaneMain.setName(""); // NOI18N
        tabpaneMain.setOpaque(true);
        tabpaneMain.setSize(new java.awt.Dimension(300, 300));

        pnlHomeScreen.setBackground(new java.awt.Color(255, 255, 255));
        pnlHomeScreen.setPreferredSize(new java.awt.Dimension(1203, 701));

        txtPane1.setEditable(false);
        txtPane1.setBackground(new java.awt.Color(51, 102, 255));
        txtPane1.setBorder(null);
        txtPane1.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 36)); // NOI18N
        txtPane1.setForeground(new java.awt.Color(255, 255, 255));
        txtPane1.setText(" \n    Easy to Use");
        jScrollPane1.setViewportView(txtPane1);

        txtPane2.setEditable(false);
        txtPane2.setBackground(new java.awt.Color(51, 102, 255));
        txtPane2.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 36)); // NOI18N
        txtPane2.setForeground(new java.awt.Color(255, 255, 255));
        txtPane2.setText("\n   Never miss \n        a   BID");
        jScrollPane2.setViewportView(txtPane2);

        txtpane3.setEditable(false);
        txtpane3.setBackground(new java.awt.Color(51, 102, 255));
        txtpane3.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 36)); // NOI18N
        txtpane3.setForeground(new java.awt.Color(255, 255, 255));
        txtpane3.setText("\n  Save Time");
        jScrollPane3.setViewportView(txtpane3);

        lblWelcomeMessage.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 36)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(51, 102, 255));
        lblWelcomeMessage.setText("Welcome to Bidmore");

        lblDescription.setBackground(new java.awt.Color(255, 255, 255));
        lblDescription.setFont(new java.awt.Font("Baloo Bhaina 2", 0, 14)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(51, 102, 255));
        lblDescription.setText("Transform your auction experience with Bidmore, the comprehensive auction management system designed to help you bid better and win more.");

        lblWhyChooseUS.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 36)); // NOI18N
        lblWhyChooseUS.setForeground(new java.awt.Color(51, 102, 255));
        lblWhyChooseUS.setText("Why choose bidmore?");

        javax.swing.GroupLayout pnlHomeScreenLayout = new javax.swing.GroupLayout(pnlHomeScreen);
        pnlHomeScreen.setLayout(pnlHomeScreenLayout);
        pnlHomeScreenLayout.setHorizontalGroup(
            pnlHomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeScreenLayout.createSequentialGroup()
                .addGroup(pnlHomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeScreenLayout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(lblWelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHomeScreenLayout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(lblWhyChooseUS, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHomeScreenLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlHomeScreenLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        pnlHomeScreenLayout.setVerticalGroup(
            pnlHomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescription)
                .addGap(18, 18, 18)
                .addComponent(lblWhyChooseUS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(pnlHomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        tabpaneMain.addTab("        HOME     ", pnlHomeScreen);

        pnlProductView.setBackground(new java.awt.Color(255, 255, 255));

        tblProductList.setAutoCreateRowSorter(true);
        tblProductList.setBackground(new java.awt.Color(153, 204, 255));
        tblProductList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tblProductList.setFont(new java.awt.Font("Baloo Bhaina 2", 0, 18)); // NOI18N
        tblProductList.setForeground(new java.awt.Color(0, 0, 0));
        tblProductList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Type", "Base Price", "Description", "Auctioneer", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductList.setGridColor(new java.awt.Color(255, 255, 255));
        tblProductList.setSelectionBackground(new java.awt.Color(51, 102, 255));
        tblProductList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblProductList.setShowGrid(true);
        tblProductList.getTableHeader().setReorderingAllowed(false);
        spTblProduct.setViewportView(tblProductList);

        lblTableHeader.setFont(new java.awt.Font("Baloo Bhaina 2", 0, 18)); // NOI18N
        lblTableHeader.setForeground(new java.awt.Color(0, 0, 0));
        lblTableHeader.setText("   Product Information");
        lblTableHeader.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnSortByProductId.setBackground(new java.awt.Color(255, 255, 255));
        btnSortByProductId.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSortByProductId.setForeground(new java.awt.Color(51, 102, 255));
        btnSortByProductId.setText("Sort by Product Id ");
        btnSortByProductId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnSortByProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByProductIdActionPerformed(evt);
            }
        });

        txtFldSearchBar.setBackground(new java.awt.Color(255, 255, 255));
        txtFldSearchBar.setFont(new java.awt.Font("Baloo Bhaina 2", 0, 12)); // NOI18N
        txtFldSearchBar.setForeground(new java.awt.Color(51, 102, 255));
        txtFldSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldSearchBarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 14)); // NOI18N
        jButton1.setText("Search ");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        btnSortByName.setBackground(new java.awt.Color(255, 255, 255));
        btnSortByName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSortByName.setForeground(new java.awt.Color(51, 102, 255));
        btnSortByName.setText("Sort by Name ");
        btnSortByName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnSortByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByNameActionPerformed(evt);
            }
        });

        btnSortByBasePrice.setBackground(new java.awt.Color(255, 255, 255));
        btnSortByBasePrice.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSortByBasePrice.setForeground(new java.awt.Color(51, 102, 255));
        btnSortByBasePrice.setText("Sort by Base Price ");
        btnSortByBasePrice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        btnSortByBasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByBasePriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProductViewLayout = new javax.swing.GroupLayout(pnlProductView);
        pnlProductView.setLayout(pnlProductViewLayout);
        pnlProductViewLayout.setHorizontalGroup(
            pnlProductViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductViewLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(spTblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductViewLayout.createSequentialGroup()
                .addGroup(pnlProductViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlProductViewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtFldSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(btnSortByProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductViewLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblTableHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSortByName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductViewLayout.createSequentialGroup()
                        .addGap(847, 847, 847)
                        .addComponent(btnSortByBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );
        pnlProductViewLayout.setVerticalGroup(
            pnlProductViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductViewLayout.createSequentialGroup()
                .addGroup(pnlProductViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductViewLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlProductViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFldSearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSortByProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSortByBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlProductViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTableHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSortByName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        tabpaneMain.addTab("View", pnlProductView);

        pnlAdmin.setBackground(new java.awt.Color(255, 255, 255));

        pnlAddProduct.setBackground(new java.awt.Color(51, 102, 255));

        txtFldProductID.setBackground(new java.awt.Color(255, 255, 255));
        txtFldProductID.setForeground(new java.awt.Color(51, 51, 255));
        txtFldProductID.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2), "Product ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N
        txtFldProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldProductIDActionPerformed(evt);
            }
        });

        txtFldProductName.setBackground(new java.awt.Color(255, 255, 255));
        txtFldProductName.setForeground(new java.awt.Color(51, 51, 255));
        txtFldProductName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2), "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        txtFldBasePrice.setBackground(new java.awt.Color(255, 255, 255));
        txtFldBasePrice.setForeground(new java.awt.Color(51, 153, 255));
        txtFldBasePrice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2), "Base Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        txtFldAuctioneer.setBackground(new java.awt.Color(255, 255, 255));
        txtFldAuctioneer.setForeground(new java.awt.Color(51, 102, 255));
        txtFldAuctioneer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2), "Auctioneer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        txtFldProductType.setBackground(new java.awt.Color(255, 255, 255));
        txtFldProductType.setForeground(new java.awt.Color(51, 102, 255));
        txtFldProductType.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2), "Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        btnUpdate3.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate3.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 18)); // NOI18N
        btnUpdate3.setForeground(new java.awt.Color(51, 102, 255));
        btnUpdate3.setText("Update");

        btnAdd3.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd3.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 18)); // NOI18N
        btnAdd3.setForeground(new java.awt.Color(51, 102, 255));
        btnAdd3.setText("Add");
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(51, 102, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtFldDescription.setBackground(new java.awt.Color(255, 255, 255));
        txtFldDescription.setForeground(new java.awt.Color(51, 102, 255));
        txtFldDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 2), "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        comboBoxStatus.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        comboBoxStatus.setForeground(new java.awt.Color(51, 102, 255));
        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UPCOMING", "ACTIVE", "SOLD", "CLOSED", " ", " " }));
        comboBoxStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxStatusActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Status");

        btnDelete4.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete4.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 18)); // NOI18N
        btnDelete4.setForeground(new java.awt.Color(51, 102, 255));
        btnDelete4.setText("Delete");
        btnDelete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddProductLayout = new javax.swing.GroupLayout(pnlAddProduct);
        pnlAddProduct.setLayout(pnlAddProductLayout);
        pnlAddProductLayout.setHorizontalGroup(
            pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddProductLayout.createSequentialGroup()
                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAddProductLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddProductLayout.createSequentialGroup()
                                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtFldProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddProductLayout.createSequentialGroup()
                                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFldAuctioneer, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddProductLayout.createSequentialGroup()
                                            .addComponent(txtFldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtFldProductType, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtFldDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnDelete4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlAddProductLayout.createSequentialGroup()
                                            .addComponent(txtFldBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(183, 183, 183)
                                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)))))))
                    .addGroup(pnlAddProductLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(btnUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
        );
        pnlAddProductLayout.setVerticalGroup(
            pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddProductLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFldProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFldProductType, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldAuctioneer, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddProductLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlAddProductLayout.createSequentialGroup()
                        .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddProductLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFldBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlAddProductLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(pnlAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );

        lblAdminHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblAdminHeader.setFont(new java.awt.Font("Baloo Bhaina 2", 0, 14)); // NOI18N
        lblAdminHeader.setForeground(new java.awt.Color(51, 102, 255));
        lblAdminHeader.setText("Fill the form below to add product for auction.");

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdminHeader)
                    .addComponent(pnlAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(lblAdminHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        tabpaneMain.addTab("Admin", pnlAdmin);

        pnlAboutUs.setBackground(new java.awt.Color(255, 255, 255));

        lblLogoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bidmore/resources/sidebaricom.jpg"))); // NOI18N

        txtPaneCommitment.setBackground(new java.awt.Color(255, 255, 255));
        txtPaneCommitment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        txtPaneCommitment.setFont(new java.awt.Font("Baloo Bhaina 2", 0, 18)); // NOI18N
        txtPaneCommitment.setForeground(new java.awt.Color(51, 102, 255));
        txtPaneCommitment.setText("                 We're committed to:\n\n--> Creating fair market opportunities\n--> Protecting buyer and seller interests\n--> Maintaining transparent transactions\n--> Fostering a trusted trading community");
        jScrollPane4.setViewportView(txtPaneCommitment);

        txtPaneCommitment2.setBackground(new java.awt.Color(255, 255, 255));
        txtPaneCommitment2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 2, true));
        txtPaneCommitment2.setFont(new java.awt.Font("Baloo Bhaina 2", 0, 18)); // NOI18N
        txtPaneCommitment2.setForeground(new java.awt.Color(51, 102, 255));
        txtPaneCommitment2.setText("                 Features in Our Platform:\n                         Easy Bidding\n \tSecure Payments\n\tSmart Notifications\n                    Bid anytime, anywhere\n                         24/7 Support");
        jScrollPane5.setViewportView(txtPaneCommitment2);

        javax.swing.GroupLayout pnlAboutUsLayout = new javax.swing.GroupLayout(pnlAboutUs);
        pnlAboutUs.setLayout(pnlAboutUsLayout);
        pnlAboutUsLayout.setHorizontalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutUsLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(lblLogoIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAboutUsLayout.setVerticalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutUsLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(lblLogoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        tabpaneMain.addTab("About Us", pnlAboutUs);

        pnlSideBar.setBackground(new java.awt.Color(255, 255, 255));

        lblSideBarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bidmore/resources/sidebaricom.jpg"))); // NOI18N
        lblSideBarIcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true));

        javax.swing.GroupLayout pnlSideBarLayout = new javax.swing.GroupLayout(pnlSideBar);
        pnlSideBar.setLayout(pnlSideBarLayout);
        pnlSideBarLayout.setHorizontalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarLayout.createSequentialGroup()
                .addComponent(lblSideBarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlSideBarLayout.setVerticalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSideBarIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tabpaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addComponent(pnlSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabpaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLoginScreen.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginScreen.setPreferredSize(new java.awt.Dimension(1203, 701));

        txtFldLoginUserName.setBackground(new java.awt.Color(255, 255, 255));
        txtFldLoginUserName.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        txtFldLoginUserName.setForeground(new java.awt.Color(51, 51, 255));
        txtFldLoginUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));
        txtFldLoginUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldLoginUserNameActionPerformed(evt);
            }
        });

        pswrdFldLoginPassword.setBackground(new java.awt.Color(255, 255, 255));
        pswrdFldLoginPassword.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        pswrdFldLoginPassword.setForeground(new java.awt.Color(51, 51, 255));
        pswrdFldLoginPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));
        pswrdFldLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswrdFldLoginPasswordActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 13)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(51, 51, 255));
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 13)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(51, 51, 255));
        lblPassword.setText("Password");

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bidmore/resources/usericon.png"))); // NOI18N

        lblPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bidmore/resources/passwordicon.png"))); // NOI18N

        lblBidmoreLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bidmore/resources/loginscreenicon.png"))); // NOI18N

        lblloginerror.setForeground(new java.awt.Color(255, 51, 51));

        pnlButton.setBackground(new java.awt.Color(51, 51, 255));
        pnlButton.setForeground(new java.awt.Color(51, 51, 255));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(51, 102, 255));
        btnLogin.setLabel("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        lblLoginHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblLoginHeader.setFont(new java.awt.Font("Baloo Bhaina 2", 1, 36)); // NOI18N
        lblLoginHeader.setForeground(new java.awt.Color(51, 102, 255));
        lblLoginHeader.setText("--> Login Here <--");

        javax.swing.GroupLayout pnlLoginScreenLayout = new javax.swing.GroupLayout(pnlLoginScreen);
        pnlLoginScreen.setLayout(pnlLoginScreenLayout);
        pnlLoginScreenLayout.setHorizontalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                        .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPasswordIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pswrdFldLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername)
                            .addComponent(txtFldLoginUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword)
                            .addComponent(lblloginerror, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLoginHeader))
                        .addGap(435, 435, 435))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                        .addComponent(lblBidmoreLogo)
                        .addGap(346, 346, 346))))
        );
        pnlLoginScreenLayout.setVerticalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblBidmoreLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(lblLoginHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblloginerror, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFldLoginUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPassword))
                    .addComponent(lblUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addComponent(lblPasswordIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244))
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addComponent(pswrdFldLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoginScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlLoginScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    // Method to add student data and populate the table
    private void registerProduct(ProductModel product) {
        productList.add(product);
        DefaultTableModel model = (DefaultTableModel) tblProductList.getModel();
        model.addRow(new Object[]{
            product.getProductId(), product.getName(), product.getType(),
            product.getBasePrice(), product.getDescription(), product.getAuctioneerName(),product.getStatus()
        });
    }
    
    
    
    
    
    
    
    
    /**
     * Switches the application screen to the specified screen name.
     *
     * @param screenName The name of the screen to display.
     */
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    
    private void txtFldLoginUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldLoginUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldLoginUserNameActionPerformed

    private void pswrdFldLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswrdFldLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswrdFldLoginPasswordActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Get the username and password input
        String username = txtFldLoginUserName.getText();
        String password = new String(pswrdFldLoginPassword.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            lblloginerror.setText("    Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) {
            lblloginerror.setText("        Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            lblloginerror.setText(""); // Clear any previous error messages
            loadScreen("MainScreen"); // Load the main screen
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtFldProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldProductIDActionPerformed

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        boolean isValid = true;

        // Validating Product ID        
        try {
            int productId = Integer.parseInt(txtFldProductID.getText().trim());

            if (productId <= 0) {
                showDialogBox("Product Id must positive", "Invalid Product Id", JOptionPane.WARNING_MESSAGE);
                isValid = false;
            } 

        } 
        catch (NumberFormatException e) {
            showDialogBox("Product Id must a number ", "Invalid Product Id", JOptionPane.WARNING_MESSAGE);
            isValid = false;
        }
      
        
        // Validating Base Price     
        try {
            int basePrice = Integer.parseInt(txtFldBasePrice.getText().trim());

            if (basePrice <= 0) {
                showDialogBox("Base Price  must positive", "Invalid Base Price", JOptionPane.WARNING_MESSAGE);
                isValid = false;
            } 

        } 
        catch (NumberFormatException e) {
            showDialogBox("Base Price must a number", "Invalid Base Price", JOptionPane.WARNING_MESSAGE);
            isValid = false;
        }
        
        
        
       String selectedStatus = comboBoxStatus.getSelectedItem().toString();
        

       

        if (isValid) {
            // Create a ProductModel instance
            ProductModel newProduct = new ProductModel(Integer.parseInt(txtFldProductID.getText().trim()),txtFldProductName.getText().trim(),txtFldProductType.getText().trim(),Integer.parseInt(txtFldBasePrice.getText().trim()),txtFldDescription.getText().trim(),txtFldAuctioneer.getText().trim(),selectedStatus);
                
            

            // Check for duplicate Product  ID
            if (checkDuplicateProduct(newProduct)) {
                txtFldProductID.setBorder(createTitledBorder(new Color(255, 51, 0), "Product Id"));
                showDialogBox("Product already exists.", "Duplicate Entry", JOptionPane.WARNING_MESSAGE);
            } else {
                // Add the product if no duplicate is found
                productList.add(newProduct);
                clearProductForm();
                loadListToTable(productList);
                txtFldProductID.setBorder(createTitledBorder(new Color(239, 192, 32), "LMU ID"));
                showDialogBox("Product added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAdd3ActionPerformed

    
     
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearProductForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void comboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxStatusActionPerformed

    private void btnDelete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete4ActionPerformed

    private void btnSortByProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByProductIdActionPerformed
        SelectionSort selectionSort = new SelectionSort();
        loadListToTable(selectionSort.sortByProductId(productList, false));
        
    }//GEN-LAST:event_btnSortByProductIdActionPerformed

    private void txtFldSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldSearchBarActionPerformed
        SelectionSort selectionSort = new SelectionSort();
        List<ProductModel> sortedList = selectionSort.sortByName(productList, false);
        
        BinarySearch search = new BinarySearch();
        ProductModel searchedData = search.searchByName(txtFldSearchBar.getText().trim(), sortedList, 0, sortedList.size()-1);
        if(searchedData!=null){
            System.out.println(searchedData.getName());
        }else{
            System.out.println("Product Not Found");
        }
    }//GEN-LAST:event_txtFldSearchBarActionPerformed

    private void btnSortByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByNameActionPerformed
        InsertionSort insertionSort = new InsertionSort();
        loadListToTable(insertionSort.sortByName(productList, false));
    }//GEN-LAST:event_btnSortByNameActionPerformed

    private void btnSortByBasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByBasePriceActionPerformed
        MergeSort mergeSort = new MergeSort();
        loadListToTable(mergeSort.sortByBasePrice(productList, false));
    }//GEN-LAST:event_btnSortByBasePriceActionPerformed

    /**
     * Creates a custom TitledBorder with specified color and title.
     *
     * @param color the color for the border and title
     * @param title the title text for the border
     * @return a TitledBorder instance
     */
    private javax.swing.border.TitledBorder createTitledBorder(Color color, String title) {
        return javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(color, 2),
                title,
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", 1, 12),
                color
        );
    }
    
    /**
     * Displays a message dialog box with the given message, title, and type.
     *
     * @param message the message to display
     * @param title the title of the dialog box
     * @param messageType the type of message (e.g., information, warning, or
     * error)
     */
    private void showDialogBox(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }
    
   
    
    
    /**
     * Checks whether a student with the same LMU ID already exists in the
     * student list.
     *
     * @param student the StudentModel object to check for duplicates
     * @return true if a duplicate is found, false otherwise
     */
    private boolean checkDuplicateProduct(ProductModel product) {
        return productList.stream()
                .anyMatch(existingProduct
                        -> existingProduct.getProductId() == product.getProductId());
    }
    
    
    /**
     * Clears all input fields in the student form. Resets each field's value to
     * an empty string.
     */
    private void clearProductForm() {
        txtFldProductID.setText("");
        txtFldProductName.setText("");
        txtFldProductType.setText("");
        txtFldBasePrice.setText("");
        txtFldDescription.setText("");
        txtFldAuctioneer.setText("");
        
        
    }

    
    
    /**
     * Populates the JTable with the current list of student records. Clears
     * existing rows in the table model before adding new data.
     */
    private void loadListToTable(List<ProductModel> productList) {
        DefaultTableModel model = (DefaultTableModel) tblProductList.getModel();

        // Clear existing rows if needed
        model.setRowCount(0);

        // Populate the table with student data
        productList.forEach(product -> model.addRow(new Object[]{
            product.getProductId(),
            product.getName(),
            product.getType(),
            product.getBasePrice(),
            product.getDescription(),
            product.getAuctioneerName(),
            product.getStatus()
            
        }));
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bidmoreapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bidmoreapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bidmoreapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bidmoreapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bidmoreapp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete4;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSortByBasePrice;
    private javax.swing.JButton btnSortByName;
    private javax.swing.JButton btnSortByProductId;
    private javax.swing.JButton btnUpdate3;
    private javax.swing.JComboBox<String> comboBoxStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAdminHeader;
    private javax.swing.JLabel lblBidmoreLogo;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblLoginHeader;
    private javax.swing.JLabel lblLogoIcon;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordIcon;
    private javax.swing.JLabel lblSideBarIcon;
    private javax.swing.JLabel lblTableHeader;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JLabel lblWhyChooseUS;
    private javax.swing.JLabel lblloginerror;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JPanel pnlAddProduct;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlHomeScreen;
    private javax.swing.JPanel pnlLoginScreen;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JPanel pnlProductView;
    private javax.swing.JPanel pnlSideBar;
    private javax.swing.JPasswordField pswrdFldLoginPassword;
    private javax.swing.JScrollPane spTblProduct;
    private javax.swing.JTabbedPane tabpaneMain;
    private javax.swing.JTable tblProductList;
    private javax.swing.JTextField txtFldAuctioneer;
    private javax.swing.JTextField txtFldBasePrice;
    private javax.swing.JTextField txtFldDescription;
    private javax.swing.JTextField txtFldLoginUserName;
    private javax.swing.JTextField txtFldProductID;
    private javax.swing.JTextField txtFldProductName;
    private javax.swing.JTextField txtFldProductType;
    private java.awt.TextField txtFldSearchBar;
    private javax.swing.JTextPane txtPane1;
    private javax.swing.JTextPane txtPane2;
    private javax.swing.JTextPane txtPaneCommitment;
    private javax.swing.JTextPane txtPaneCommitment2;
    private javax.swing.JTextPane txtpane3;
    // End of variables declaration//GEN-END:variables
}
